org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
kotlin.native.ignoreDisabledTargets=true
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C:/Program Files/Android/Android Studio/jbr
